watch_stylesheet: true
watch_config: true
debug: true

bars:
  status-bar:
    enabled: true
    screens: ['*']
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: true
    blur_effect:
      enabled: false 
      acrylic: true 
      dark_mode: false
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: true
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 35
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left:
        [
          "cpu",
          "memory",
          "apps",
          "windows_workspaces",
        ]
      center: ["clock"]
      right:
        [
          "active_window",
          "media_player",
          "bluetooth",
          "battery",
        ]

widgets:
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[process][name]}"
      label_alt: "{win[process][name]}"
      label_no_window: ""
      label_icon: true
      label_icon_size: 16
      max_length: 20
      max_length_ellipsis: "..."
      monitor_exclusive: false
      rewrite:
        - pattern: "^(.+?)\\.[eE][xX][eE]$"
          replacement: "\\1"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]

  clock:
      type: "yasb.clock.ClockWidget"
      options:
        label: "{%a %I:%M %p}"
        label_alt: "{%A %d %B %Y %I:%M %p}"
        #timezones: ["Europe/London", "America/New_York"]
        timezones: []
        label_shadow:
          enabled: true
          color: "black"
          radius: 3
          offset: [ 1, 1 ]
        callbacks:
          on_middle: "exec explorer.exe shell:Appsfolder\\Microsoft.WindowsAlarms_8wekyb3d8bbwe!App"
          on_right: "next_timezone"

  cpu:
      type: "yasb.cpu.CpuWidget"
      options:
        label: "<span>\uf2db</span> {info[percent][total]}%"
        label_alt: "<span>\uf437</span> {info[histograms][cpu_percent]}"
        update_interval: 1000
        histogram_icons:
          - "\u2581" # 0%
          - "\u2581" # 10%
          - "\u2582" # 20%
          - "\u2583" # 30%
          - "\u2584" # 40%
          - "\u2585" # 50%
          - "\u2586" # 60%
          - "\u2587" # 70%
          - "\u2588" # 80%+
        histogram_num_columns: 10
        label_shadow:
          enabled: true
          color: "black"
          radius: 3
          offset: [ 1, 1 ]
        callbacks:
          on_right: "exec cmd /c Taskmgr"

  memory:
      type: "yasb.memory.MemoryWidget"
      options:
        label: "<span>\uefc5</span> {virtual_mem_percent}% <span class='MenuDivider'></span>"
        label_alt: "<span>\uefc5</span> {virtual_mem_used} / {virtual_mem_total} <span class='MenuDivider'></span>"
        update_interval: 1000
        label_shadow:
          enabled: true
          color: "black"
          radius: 3
          offset: [ 1, 1 ]
        callbacks:
          on_right: "exec cmd /c Taskmgr"

  disk:
      type: "yasb.disk.DiskWidget"
      options:
          label: "<span>\udb80\udeca</span>{volume_label} {space[used][percent]}"
          label_alt: "<span>\udb80\udeca</span>{volume_label} {space[used][gb]} / {space[total][gb]}"
          volume_label: "C"
          update_interval: 60 # Update interval in seconds
          callbacks:
            on_middle: "do_nothing"
            on_right: "exec explorer C:\\" # Open disk C in file explorer

  media_player:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title}"
      label_alt: "{title}"
      max_field_size:
        label: 20
        label_alt: 0
      show_thumbnail: false
      controls_only: false
      controls_left: true
      hide_empty: true
      thumbnail_alpha: 255
      thumbnail_padding: 0
      thumbnail_edge_fade: true
      icons:
        prev_track: "\uf048"
        next_track: "\uf051"
        play: "\uf04b"
        pause: "\uf04c"
      scrolling_label:
        enabled: false
        update_interval_ms: 30
        style: "left"  # can be "left", "right", "bounce", "bounce-ease"
        separator: " | "
        label_padding: 1
      # Easing curve params: https://www.desmos.com/calculator/j7eamemxzi
        ease_slope: 20
        ease_pos: 0.8
        ease_min: 0.5
      media_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 60
        thumbnail_corner_radius: 8
        thumbnail_size: 120
        max_title_size: 27
        max_artist_size: 60
        show_source: false
      media_menu_icons:
        prev_track: "\uf048"
        next_track: "\uf051"
        play: "\uf04b"
        pause: "\uf04c"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      label_shadow:
          enabled: true
          color: "black"
          radius: 3
          offset: [ 1, 1 ]
      callbacks:
        on_left: "toggle_media_menu"
        on_right: "toggle_play_pause"

  traffic:
    type: "yasb.traffic.TrafficWidget"
    options:
      label: "<span class='download'>\udb81\udf2e</span> <span class='download-text'>{download_speed}</span><span class='divider'>|</span><span class='upload-text'>{upload_speed}</span><span class='upload'>\udb81\udf37</span><span class='MenuDivider'></span>"
      label_alt: "<span class='download'>\udb81\udf2e</span> <span class='download-text'>{download_speed}</span><span class='divider'>|</span><span class='upload-text'>{upload_speed}</span><span class='upload'>\udb81\udf37</span><span class='MenuDivider'></span>"
      update_interval: 1000
      callbacks:
        on_right: "exec cmd /c Taskmgr"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      label_shadow:
        enabled: true
        color: "black"
        radius: 5
        offset: [0, 0]

  power_menu:
      type: "yasb.power_menu.PowerMenuWidget"
      options:
        label: "<span>\ue62a</span>"
        blur_background: true
        animation_duration: 200 # Milisecond 
        button_row: 3 # Number of buttons in row, min 1 max 5
        buttons:
          lock: ["\ue72e","Lock"]
          # signout: ["\udb80\udf43","Sign out"]
          sleep: ["\uf1db","Sleep"]
          shutdown: ["\ue7e8","Shut Down"]
          restart: ["\ue777","Restart"]
          hibernate: ["\ue823","Hibernate"]
          cancel: ["\ue711","Cancel"]
          #force_shutdown: ["\uf011","Force Shut Down"]
          #force_restart: ["\uead2","Force Restart"]

  ip_info:
      type: "yasb.custom.CustomWidget"
      options:
        label: "\uf3c5 {data[city]}, {data[region]}"
        label_alt: "\uf3c5 {data[ip]} [{data[country]}]"
        class_name: "ip-info-widget"
        exec_options:
          run_cmd: "curl.exe https://ipinfo.io"
          run_interval: 120000                                        # every 5 minutes
          return_format: "json"
        callbacks:
          on_left: "toggle_label"
          on_middle: "exec cmd /c ncpa.cpl"                           # open network settings
          on_right: "exec cmd /c start https://ipinfo.io/{data[ip]} " # open ipinfo in browser

  lang:
      type: "yasb.custom.CustomWidget"
      options:
        label: "\udb80\udf0c {data}"
        label_alt: "\udb81\udfd3 {data}"
        class_name: "lang-widget"
        exec_options:
          run_cmd: "powershell add-type -assemblyname system.windows.forms;([system.windows.forms.inputlanguage]::currentinputlanguage).Culture.Name"
          # run every 3 sec
          run_interval: 3000
          return_format: "string"

  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      icon_size: 18
      tooltip: true
      show_only_visible: false
      strict_filtering: true
      monitor_exclusive: false
      animation:
        enabled: true
      preview:
        enabled: true
        width: 240
        delay: 400
        padding: 8
        margin: 8
      title_label:
        enabled: false
        show: "always"
        min_length: 10
        max_length: 30
      ignore_apps:
        processes: []
        titles: []
        classes: []

  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "{icon} {percent}%"
      label_alt: "{icon} {percent}% | Zeit: {time_remaining}"
      charging_options:
        icon_format: "{charging_icon}"
      status_icons:
        icon_charging: "\udb80\udc84"
        icon_critical: "\udb80\udc7a"
        icon_low: "\udb80\udc7b"
        icon_medium: "\udb80\udc7e"
        icon_high: "\udb80\udc80"
        icon_full: "\udb80\udc79"
      status_thresholds:
        critical: 10
        low: 45
        medium: 75
        high: 85
        full: 100
      label_shadow:
          enabled: true
          color: "black"
          radius: 3
          offset: [ 1, 1 ]

  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\udb80\udf5c</span>"
      menu_list:
      - { title: "Home", path: "~" }
      - { title: "Downloads", path: "~\\Downloads"}
      - { title: "Documents", path: "~\\Documents"}
      - { title: "Pictures", path: "~\\Pictures"}
      - { title: "Videos", path: "~\\Videos"}
      system_menu: true
      power_menu: false
      blur: true
      round_corners: true
      round_corners_type: "normal"
      border_color: ""
      distance: 10
      container_padding: 
        top: 0
        left: 0
        bottom: 0
        right: 0
      alignment: "left"
      direction: "down"
      menu_labels:
        shutdown: "Shutdown"
        restart: "Restart"
        logout: "Logout"
        lock: "Lock"
        sleep: "Sleep"
        system: "System Settings"
        about: "About This PC"
        task_manager: "Task Manager"

  apps:
    type: "yasb.applications.ApplicationsWidget"
    options:
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
      label: "{data}"
      app_list:
        - { icon: "Vivaldi", launch: 'C:\\Users\\infof\\.config\\yasb\\vivaldi_launcher.bat' }
        - { icon: "OneNote", launch: 'C:\\Users\\infof\\.config\\yasb\\onenote_launcher.bat' }
        - { icon: "Terminal", launch: 'C:\\Users\\infof\\.config\\yasb\\terminal_launcher.bat' }

  taskbar_toggle:
    type: "yasb.applications.ApplicationsWidget"
    options:
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
      label: "{data}"
      label_shadow:
          enabled: true
          color: "black"
          radius: 3
          offset: [ 1, 1 ]
      app_list:
        - { icon: "Vivaldi", launch: "C:\\Users\\infof\\AppData\\Local\\Vivaldi\\Application\\vivaldi.exe" }

  bluetooth:
    type: "yasb.bluetooth.BluetoothWidget"
    options:
      label: "<span>{icon}</span> {device_count}"
      label_alt: "<span>{icon}</span> {device_count}"
      label_no_device: ""
      label_device_separator: ", "
      max_length: 10
      max_length_ellipsis: "..."
      icons: 
        bluetooth_on: "\udb80\udcaf"
        bluetooth_off: "\udb80\udcb2"
        bluetooth_connected: "\udb80\udcb1"
      device_aliases:
        - name: "T5.0"
          alias: "\uf025"
      callbacks:
        on_left: "exec cmd.exe /c start ms-settings:bluetooth"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]

  windows_workspaces:
    type: "yasb.windows_desktops.WorkspaceWidget"
    options:
      label_workspace_btn: "\udb81\udc3d"
      label_workspace_active_btn: "\udb81\udc3e"
      btn_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]